name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"
max_auto_retries  = 5

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "gcp/src/components/certificate"
branch    = "am/kitchen-sink-gcp"

[vars]
install_id    = "{{ .nuon.install.id }}"
project_id    = "{{ .nuon.install_stack.outputs.project_id }}"
domain_name   = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
dns_zone_name = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.zone_id }}"
