name         = "img_worker"
type         = "docker_build"
var_name     = "img_worker"
dockerfile   = "api/Dockerfile"
dependencies = ["img_api"]

[connected_repo]
repo      = "nuonco/kitchen-sink-app"
directory = "."
branch    = "main"

[labels]
is_image = "true"
