name         = "seed_job"
type         = "job"
dependencies = ["kitchen_sink"]
image_url    = "{{.nuon.components.img_api.outputs.image.repository}}"
tag          = "{{.nuon.components.img_api.outputs.image.tag}}"
cmd          = ["sh", "-c"]
args         = ["echo 'seeding complete' && curl -sf http://kitchen-sink-api.kitchen-sink.svc.cluster.local:8080/readyz"]

[env_vars]
INSTALL_ID = "{{.nuon.install.id}}"
APP_NAME   = "kitchen-sink"
