type        = "aws-cloudformation"
name        = "nuon-kitchen-sink-{{.nuon.install.id}}"
description = "CloudFormation stack for Kitchen Sink app: Install {{.nuon.install.id}}"

vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.0/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.2.0/runner/asg/stack.yaml"
