# container-image
name     = "action_db_tools"
type     = "container_image"
var_name = "action_db_tools"

[aws_ecr]
image_url    = "431927561584.dkr.ecr.us-west-2.amazonaws.com/kitchen-sink-components"
update_policy = "~1.0.0"
region       = "us-west-2"
iam_role_arn = "arn:aws:iam::431927561584:role/kitchen-sink-ecr-access"

[labels]
is_image = "true"
purpose  = "container-action"
