#:schema https://api.nuon.co/v1/general/config-schema?type=install
name            = "acme-production"
approval_option = "approve-all"

[labels]
env  = "production"
tier = "customer"

[gcp_account]
project_id = "acme-kitchen-sink-prod"
region     = "us-west1"

[[inputs]]
debug_mode = "false"

[[inputs]]
db_tier = "db-custom-1-3840"

[[inputs]]
domain = "example.com"

[component_toggles]
audit_log_exporter = false
tictactoe          = false
