name               = "app_healthcheck"
image              = "{{.nuon.components.action_curl.outputs.image.ref}}"
timeout            = "2m"
enable_kube_config = false
dependencies       = ["action_curl", "application_load_balancer"]

[[triggers]]
type = "manual"

[[steps]]
name            = "check-livez"
inline_contents = "./app_healthcheck/healthcheck.sh"

[steps.env_vars]
ENDPOINT = "https://app.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
IMAGE    = "{{.nuon.components.action_curl.outputs.image.ref}}"

[labels]
runtime = "container"
sample  = "health-check"
