name                              = "terraform_tags"
type                              = "terraform_module"
terraform_version                 = "1.9.0"
drift_schedule                    = "0 0 * * *"
max_auto_retries                  = 3
skip_noops                        = true
auto_approve_on_policies_passing  = true

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "components/terraform"
branch    = "main"

[vars]
install_id = "{{.nuon.install.id}}"
app_name   = "kitchen-sink"
region     = "{{.nuon.install_stack.outputs.region}}"

[[var_file]]
contents = "./values/terraform-tags.tfvars"

[labels]
custom_component_type = "terraform"
