name = "demo"

[connected_repo]
repo      = "nuonco/kitchen-sink"
branch    = "main"
directory = "."

[[install_groups]]
name          = "demo"
order         = 0
install_names = ["healthcheck-demo-001"]
