name = "main"

[connected_repo]
repo = "nuonco/kitchen-sink"
branch = "main"
directory = "."

[[install_groups]]
name = "stage"
order = 0
labels = { "env" = "stage" }

[[install_groups]]
name = "prod"
order = 0
labels = { "env" = "prod" }
