[[role]]
name         = "{{.nuon.install.id}}-app-break-glass"
display_name = "Break Glass Admin"
description  = "elevated role for emergency workload restarts; admin access minus Secrets Manager"

[[role.policies]]
managed_policy_name = "AdministratorAccess"

[[role.policies]]
name     = "remove-secrets-manager"
contents = """
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": "secretsmanager:*",
            "Resource": "*"
        }
    ]
}
"""
