# policies

[[policy]]
type       = "terraform_module"
engine     = "opa"
components = ["*"]
contents   = "./policies/deny-public-s3-bucket.rego"

[[policy]]
type       = "helm_chart"
engine     = "opa"
components = ["kitchen_sink"]
contents   = "./policies/deny-public-api-ingress.rego"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/sandbox-limits.rego"
