# Kubernetes cluster policies (Kyverno)
[[policy]]
type     = "kubernetes_cluster"
contents = "./disallow-ingress-nginx-custom-snippets.yml"

[[policy]]
type     = "kubernetes_cluster"
contents = "https://raw.githubusercontent.com/kyverno/policies/main/best-practices/disallow-latest-tag/disallow-latest-tag.yaml"
