type        = "aws-cloudformation"
name        = "nuon-kitchen-sink-{{.nuon.install.id}}"
description = "CloudFormation stack for Kitchen Sink install {{.nuon.install.id}}"

# Nested stack templates for VPC and runner infrastructure
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.6/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.1.6/runner/asg/stack.yaml"
