[[rules]]
name = "component-health-ja-healthchecks-010"
trigger = "kitchen-sink-health"
event_types = ["component.health"]

[[rules.filters]]
from = "payload"
op = "eq"
path = "$.install"
value = "inl4i439ejcvwesdqhovsh3plk"

[rules.target]
type = "runbook"
runbook = "report-health"
install = "ja-healthchecks-010"

[rules.target.inputs]
install = "$.install"
component = "$.component"
check = "$.check"
status = "$.status"
message = "$.message"
details = "$.details"
