name    = "db_seed"
image   = "postgres:17-alpine"
timeout = "5m"

[[triggers]]
type           = "pre-deploy-component"
component_name = "kitchen_sink"

[[triggers]]
type = "manual"

[[steps]]
name    = "seed database"
inline_contents = "./db_seed/seed.sh"

[steps.env_vars]
PGHOST            = "{{.nuon.install_stack.outputs.custom_nested_stacks.rds_instance.outputs.DBEndpoint}}"
PGPORT            = "{{.nuon.install_stack.outputs.custom_nested_stacks.rds_instance.outputs.DBPort}}"
PGUSER            = "kitchensink"
PGDATABASE        = "postgres"
PGPASSWORD        = "temp-password-123"
PGCONNECT_TIMEOUT = "10"
