# install
name = "Customer B"
app_branch = "continuous-release"
approval_option = "approve-all"

[labels]
mode = "push"

[telemetry]
enabled = true

[aws_account]
region = "us-west-2"

[[inputs]]
debug_mode = "false"

[[inputs]]
domain = "nuon.run"

[[inputs]]
telemetry_demo_profile = "noisy"

[component_toggles]
audit_log_exporter = false
tictactoe = false
