// GENERATED by scripts/gen-config-data.mjs from git: each case branch's
// diff against main and its own branch.toml. Do not edit. Committed because
// the image build has no repo; regenerated from any checkout that has the
// three branches.

import type { InstallGroup } from './config-data.gen'

export interface DeltaFile {
  path: string
  /** git name-status with --no-renames: M, A, or D. */
  status: string
  /** Removed and added lines, comments and blank lines dropped. */
  minus: string[]
  plus: string[]
}

export interface CaseBranch {
  branch: string
  /** The `name` in the branch's own branch.toml. */
  branchName: string
  /** The git branch its branch.toml tracks. */
  trackedBranch: string
  base: string
  baseCommit: string
  head: string
  /** The install groups the branch's branch.toml declares, in order. */
  groups: InstallGroup[]
  files: DeltaFile[]
}

export const caseBranches: Record<string, CaseBranch> = {
  "no-egress": {
    "branch": "no-egress",
    "branchName": "no-egress",
    "trackedBranch": "no-egress",
    "base": "main",
    "baseCommit": "5e45643",
    "head": "3863ce7",
    "groups": [
      {
        "name": "enterprise",
        "order": 3,
        "selector": "env = production · tier = enterprise"
      }
    ],
    "files": [
      {
        "path": "branch.toml",
        "status": "M",
        "minus": [
          "name = \"main\"",
          "branch    = \"main\"",
          "[[install_groups]]",
          "name  = \"staging\"",
          "order = 1",
          "use_for_previews = true",
          "[install_groups.label_selector]",
          "env = \"staging\"",
          "[[install_groups]]",
          "name  = \"customers\"",
          "order = 2",
          "[install_groups.label_selector]",
          "env  = \"production\"",
          "tier = \"customer\""
        ],
        "plus": [
          "name = \"no-egress\"",
          "branch    = \"no-egress\""
        ]
      },
      {
        "path": "policies/deny-nat.rego",
        "status": "A",
        "minus": [],
        "plus": [
          "package nuon",
          "deny contains msg if {",
          "    resource := input.plan.resource_changes[_]",
          "    resource.type == \"aws_nat_gateway\"",
          "    resource.change.actions[_] in [\"create\", \"update\"]",
          "    msg := sprintf(\"NAT gateway '%s' is not allowed in this sandbox\", [resource.address])",
          "}"
        ]
      },
      {
        "path": "policies/deny-nat.toml",
        "status": "A",
        "minus": [],
        "plus": [
          "type     = \"sandbox\"",
          "engine   = \"opa\"",
          "contents = \"./deny-nat.rego\""
        ]
      },
      {
        "path": "sandbox.tfvars",
        "status": "M",
        "minus": [],
        "plus": [
          "cluster_endpoint_public_access = false"
        ]
      }
    ]
  },
  "byo-vpc": {
    "branch": "byo-vpc",
    "branchName": "byo-vpc",
    "trackedBranch": "byo-vpc",
    "base": "main",
    "baseCommit": "5e45643",
    "head": "61081d1",
    "groups": [
      {
        "name": "enterprise",
        "order": 3,
        "selector": "env = production · tier = enterprise"
      }
    ],
    "files": [
      {
        "path": "branch.toml",
        "status": "M",
        "minus": [
          "name = \"main\"",
          "branch    = \"main\"",
          "[[install_groups]]",
          "name  = \"staging\"",
          "order = 1",
          "use_for_previews = true",
          "[install_groups.label_selector]",
          "env = \"staging\"",
          "[[install_groups]]",
          "name  = \"customers\"",
          "order = 2",
          "[install_groups.label_selector]",
          "env  = \"production\"",
          "tier = \"customer\""
        ],
        "plus": [
          "name = \"byo-vpc\"",
          "branch    = \"byo-vpc\""
        ]
      },
      {
        "path": "stack.toml",
        "status": "M",
        "minus": [
          "vpc_nested_template_url    = \"https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/vpc/eks/default/stack.yaml\""
        ],
        "plus": [
          "vpc_nested_template_url    = \"https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/byo-vpc/default/stack.yaml\""
        ]
      }
    ]
  },
  "single-tenant": {
    "branch": "single-tenant",
    "branchName": "single-tenant",
    "trackedBranch": "single-tenant",
    "base": "main",
    "baseCommit": "5e45643",
    "head": "c106f9e",
    "groups": [
      {
        "name": "customers",
        "order": 2,
        "selector": "env = production · tier = customer"
      }
    ],
    "files": [
      {
        "path": "branch.toml",
        "status": "M",
        "minus": [
          "name = \"main\"",
          "branch    = \"main\"",
          "[[install_groups]]",
          "name  = \"staging\"",
          "order = 1",
          "use_for_previews = true",
          "[install_groups.label_selector]",
          "env = \"staging\"",
          "[[install_groups]]",
          "name  = \"enterprise\"",
          "order = 3",
          "[install_groups.label_selector]",
          "env  = \"production\"",
          "tier = \"enterprise\""
        ],
        "plus": [
          "name = \"single-tenant\"",
          "branch    = \"single-tenant\""
        ]
      }
    ]
  }
}
