// GENERATED by scripts/gen-config-data.mjs from the repo's app config.
// Do not edit; run `npm run build` (or the script directly) to regenerate.
// Committed because the image build's context is components/ui only, so the
// script cannot see the repo config there and keeps this file as built.

export interface InstallGroup {
  name: string
  order: number
  selector: string
}

export interface RunbookStep {
  name: string
  type: string
  detail: string
}

export interface Runbook {
  name: string
  description: string
  kind: string
  mutates: boolean
  steps: RunbookStep[]
}

export interface AdhocAction {
  name: string
  timeout: string
  triggers: string[]
  labels: string | null
  breakGlass: boolean
}

export interface Role {
  name: string
  type: string
  boundary: string
  desc: string
}

export interface Guardrail {
  name: string
  type: string
  target: string
}

export interface ToggleableComponent {
  name: string
  type: string
  defaultEnabled: boolean
  toml: string
}

export interface ComponentNode {
  name: string
  type: string
  dependencies: string[]
}

export const branchName = "main"

export const repoName = "nuonco/kitchen-sink"

export const postDeployRunbooks: string[] = [
  "full-health-check"
]

export const installGroups: InstallGroup[] = [
  {
    "name": "staging",
    "order": 1,
    "selector": "env = staging"
  },
  {
    "name": "customers",
    "order": 2,
    "selector": "env = production · tier = customer"
  },
  {
    "name": "enterprise",
    "order": 3,
    "selector": "env = production · tier = enterprise"
  }
]

export const branchConfigAbridged = "name = \"main\"\n\npost_deploy_runbooks = [\"full-health-check\"]\n\n[public_repo]\nrepo      = \"nuonco/kitchen-sink\"\ndirectory = \".\"\nbranch    = \"main\"\n\n[[install_groups]]\nname  = \"staging\"\norder = 1\n\n[install_groups.label_selector]\nenv = \"staging\"\n\n[[install_groups]]\nname  = \"customers\"\norder = 2\n\n[install_groups.label_selector]\nenv  = \"production\"\ntier = \"customer\"\n\n[[install_groups]]\nname  = \"enterprise\"\norder = 3\n\n[install_groups.label_selector]\nenv  = \"production\"\ntier = \"enterprise\""

export const runbooks: Runbook[] = [
  {
    "name": "full-health-check",
    "description": "Checks nodes, workloads, ingress, and the public endpoint.",
    "kind": "health-check",
    "mutates": false,
    "steps": [
      {
        "name": "node-health",
        "type": "action",
        "detail": "runs the health_nodes action"
      },
      {
        "name": "workload-health",
        "type": "action",
        "detail": "runs the cron_status action"
      },
      {
        "name": "rollout-convergence",
        "type": "action",
        "detail": "runs the health_rollout action"
      },
      {
        "name": "ingress-health",
        "type": "action",
        "detail": "runs the health_ingress action"
      },
      {
        "name": "endpoint-health",
        "type": "action",
        "detail": "runs the health_endpoint action"
      }
    ]
  },
  {
    "name": "debug-bundle",
    "description": "Collects pod, event, and config state into one transcript.",
    "kind": "debug",
    "mutates": false,
    "steps": [
      {
        "name": "collect-diagnostics",
        "type": "action",
        "detail": "runs the debug action"
      },
      {
        "name": "workload-detail",
        "type": "action",
        "detail": "Deployments, Pods, Pod detail · 4m"
      },
      {
        "name": "ingress-and-secrets",
        "type": "action",
        "detail": "Services and ingresses, ALB ingress detail, Synced secrets present, Config map · 3m"
      },
      {
        "name": "endpoint-probe",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 2m"
      }
    ]
  },
  {
    "name": "re-apply-config",
    "description": "Re-applies this install's components after an out-of-band change.",
    "kind": "drift",
    "mutates": true,
    "steps": [
      {
        "name": "drift-plan",
        "type": "component_deploy",
        "detail": "kitchen_sink, plan only"
      },
      {
        "name": "reconcile-sandbox",
        "type": "sandbox_reprovision",
        "detail": "sandbox infrastructure, component deploys skipped"
      },
      {
        "name": "reconcile-pulumi-infra",
        "type": "component_deploy",
        "detail": "pulumi_infra"
      },
      {
        "name": "reconcile-certificate",
        "type": "component_deploy",
        "detail": "certificate"
      },
      {
        "name": "reconcile-app",
        "type": "component_deploy",
        "detail": "kitchen_sink, dependents follow"
      },
      {
        "name": "verify",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 8m"
      }
    ]
  },
  {
    "name": "break-glass",
    "description": "Runs elevated remediation under the break-glass role, recorded.",
    "kind": "break-glass",
    "mutates": true,
    "steps": [
      {
        "name": "capture-state",
        "type": "action",
        "detail": "Pods before remediation, Recent events · 3m"
      },
      {
        "name": "elevated-remediation",
        "type": "action",
        "detail": "runs the break_glass_remediation action"
      },
      {
        "name": "verify",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 8m"
      }
    ]
  }
]

export const adhocActions: AdhocAction[] = [
  {
    "name": "cron_status",
    "timeout": "1m",
    "triggers": [
      "cron 0 * * * *",
      "manual"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "debug",
    "timeout": "2m",
    "triggers": [
      "manual"
    ],
    "labels": "kind = \"debug\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "lifecycle_hooks",
    "timeout": "1m",
    "triggers": [
      "manual",
      "post-provision",
      "post-deploy-component kitchen_sink",
      "pre-deploy-component kitchen_sink"
    ],
    "labels": "kind = \"lifecycle\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "break_glass_remediation",
    "timeout": "10m",
    "triggers": [
      "manual"
    ],
    "labels": "kind = \"break-glass\" · team = \"platform\"",
    "breakGlass": true
  },
  {
    "name": "app_healthcheck",
    "timeout": "2m",
    "triggers": [
      "manual"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\" · runtime = \"container\"",
    "breakGlass": false
  },
  {
    "name": "db_metrics",
    "timeout": "5m",
    "triggers": [
      "manual"
    ],
    "labels": "kind = \"metrics\" · team = \"platform\" · runtime = \"container\"",
    "breakGlass": false
  },
  {
    "name": "dns_check",
    "timeout": "5m",
    "triggers": [
      "manual",
      "pre-deploy-component certificate"
    ],
    "labels": "kind = \"dns\" · team = \"platform\" · runtime = \"container\"",
    "breakGlass": false
  },
  {
    "name": "health_endpoint",
    "timeout": "5m",
    "triggers": [
      "manual",
      "post-provision"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "health_ingress",
    "timeout": "3m",
    "triggers": [
      "manual",
      "post-provision"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "health_nodes",
    "timeout": "2m",
    "triggers": [
      "manual",
      "post-provision"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "health_rollout",
    "timeout": "6m",
    "triggers": [
      "manual",
      "post-provision"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\"",
    "breakGlass": false
  },
  {
    "name": "rollout_status",
    "timeout": "10m",
    "triggers": [
      "manual"
    ],
    "labels": "kind = \"health-check\" · team = \"platform\" · runtime = \"container\"",
    "breakGlass": false
  }
]

export const lifecycleHooksToml = "name         = \"lifecycle_hooks\"\ntimeout      = \"1m\"\ndependencies = [\"kitchen_sink\"]\n\n[[triggers]]\ntype = \"manual\"\n\n[[triggers]]\ntype = \"post-provision\"\n\n[[triggers]]\ntype           = \"post-deploy-component\"\ncomponent_name = \"kitchen_sink\"\n\n[[triggers]]\ntype           = \"pre-deploy-component\"\ncomponent_name = \"kitchen_sink\"\n\n[[steps]]\nname            = \"log-lifecycle-hook\"\ninline_contents = \"./lifecycle_hooks/script.sh\"\n\n[steps.env_vars]\nHOOK_VERSION = \"v1\"\n\n[labels]\nkind = \"lifecycle\"\nteam = \"platform\""

export const roles: Role[] = [
  {
    "name": "provision",
    "type": "provision",
    "boundary": "provision_boundary.json",
    "desc": "Provision the sandbox and components; trigger actions."
  },
  {
    "name": "setup",
    "type": "custom",
    "boundary": "provision_boundary.json",
    "desc": "Initial component deployment and configuration."
  },
  {
    "name": "maintenance",
    "type": "maintenance",
    "boundary": "maintenance_boundary.json",
    "desc": "Operate and remediate components."
  },
  {
    "name": "sandbox-updates",
    "type": "custom",
    "boundary": "provision_boundary.json",
    "desc": "Update and maintain sandbox infrastructure."
  },
  {
    "name": "actions",
    "type": "custom",
    "boundary": "inline policy",
    "desc": "Execute actions (healthchecks, debug, cron jobs)."
  },
  {
    "name": "deprovision",
    "type": "deprovision",
    "boundary": "deprovision_boundary.json",
    "desc": "Deprovision the sandbox and components."
  },
  {
    "name": "app-break-glass",
    "type": "break-glass",
    "boundary": "explicit Deny",
    "desc": "Grants admin access for emergencies."
  }
]

export const breakGlassToml = "[[role]]\nname         = \"{{.nuon.install.id}}-app-break-glass\"\ndisplay_name = \"Break Glass Admin\"\ndescription  = \"grants admin access for emergencies\"\n\n[[role.policies]]\nmanaged_policy_name = \"AdministratorAccess\"\n\n[[role.policies]]\nname     = \"remove-secrets-manager\"\ncontents = \"\"\"\n{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Deny\",\n            \"Action\": \"secretsmanager:*\",\n            \"Resource\": \"*\"\n        }\n    ]\n}\n\"\"\""

export const guardrails: Guardrail[] = [
  {
    "name": "cluster-requirements",
    "type": "sandbox",
    "target": "the sandbox plan"
  },
  {
    "name": "deny-public-api-ingress",
    "type": "helm_chart",
    "target": "kitchen_sink"
  },
  {
    "name": "deny-public-s3-bucket",
    "type": "terraform_module",
    "target": "all components"
  },
  {
    "name": "sandbox-limits",
    "type": "sandbox",
    "target": "the sandbox plan"
  }
]

export const toggleableComponents: ToggleableComponent[] = [
  {
    "name": "audit_log_exporter",
    "type": "kubernetes_manifest",
    "defaultEnabled": false,
    "toml": "name = \"audit_log_exporter\"\ntype = \"kubernetes_manifest\"\n\nnamespace    = \"kitchen-sink\"\ndependencies = [\"kitchen_sink\"]\n\ntoggleable      = true\ndefault_enabled = false\n\n[public_repo]\ndirectory = \".\"\nrepo      = \"nuonco/kitchen-sink\"\nbranch = \"main\"\n\n[kustomize]\npath        = \"./src/components/audit-log-exporter\"\npatches     = []\nenable_helm = false\n\n[labels]\ntoggleable = \"true\""
  },
  {
    "name": "tictactoe",
    "type": "kubernetes_manifest",
    "defaultEnabled": false,
    "toml": "name = \"tictactoe\"\ntype = \"kubernetes_manifest\"\n\nnamespace    = \"kitchen-sink\"\ndependencies = [\"kitchen_sink\"]\n\ntoggleable      = true\ndefault_enabled = false\n\n[public_repo]\ndirectory = \".\"\nrepo      = \"nuonco/kitchen-sink\"\nbranch = \"main\"\n\n[kustomize]\npath        = \"./src/components/tictactoe\"\npatches     = []\nenable_helm = false\n\n[labels]\ntoggleable = \"true\""
  }
]

export const components: ComponentNode[] = [
  {
    "name": "action_curl",
    "type": "container_image",
    "dependencies": []
  },
  {
    "name": "action_dns_check",
    "type": "container_image",
    "dependencies": []
  },
  {
    "name": "application_load_balancer",
    "type": "helm_chart",
    "dependencies": [
      "certificate",
      "kitchen_sink"
    ]
  },
  {
    "name": "audit_log_exporter",
    "type": "kubernetes_manifest",
    "dependencies": [
      "kitchen_sink"
    ]
  },
  {
    "name": "certificate",
    "type": "terraform_module",
    "dependencies": []
  },
  {
    "name": "img_api",
    "type": "container_image",
    "dependencies": []
  },
  {
    "name": "img_ui",
    "type": "container_image",
    "dependencies": []
  },
  {
    "name": "kitchen_sink",
    "type": "helm_chart",
    "dependencies": [
      "img_api",
      "img_ui"
    ]
  },
  {
    "name": "kustomize_namespace",
    "type": "kubernetes_manifest",
    "dependencies": []
  },
  {
    "name": "kustomizeapp",
    "type": "kubernetes_manifest",
    "dependencies": [
      "kustomize_namespace"
    ]
  },
  {
    "name": "pulumi_infra",
    "type": "pulumi",
    "dependencies": []
  },
  {
    "name": "tictactoe",
    "type": "kubernetes_manifest",
    "dependencies": [
      "kitchen_sink"
    ]
  }
]
