// GENERATED by scripts/gen-config-data.mjs from the repo's app config.
// Do not edit; run `npm run build` (or the script directly) to regenerate.
// Committed because the image build's context is components/ui only, so the
// script cannot see the repo config there and keeps this file as built.

export interface InstallGroup {
  name: string
  order: number
  selector: string
  preview: boolean
}

export interface RunbookStep {
  name: string
  type: string
  detail: string
}

export interface Runbook {
  name: string
  description: string
  kind: string
  mutates: boolean
  steps: RunbookStep[]
}

export interface AdhocAction {
  name: string
  timeout: string
  triggers: string[]
  labels: string | null
  breakGlass: boolean
}

export interface Role {
  name: string
  type: string
  boundary: string
  desc: string
}

export interface Guardrail {
  name: string
  type: string
  target: string
}

export interface ToggleableComponent {
  name: string
  type: string
  defaultEnabled: boolean
  toml: string
}

export const branchName = "ms/theme-conduit"

export const repoName = "nuonco/kitchen-sink"

export const postDeployRunbooks: string[] = [
  "pipeline-health-sweep"
]

export const installGroups: InstallGroup[] = [
  {
    "name": "staging",
    "order": 1,
    "selector": "env = staging",
    "preview": true
  },
  {
    "name": "customers",
    "order": 2,
    "selector": "env = production · tier = customer",
    "preview": false
  },
  {
    "name": "enterprise",
    "order": 3,
    "selector": "env = production · tier = enterprise",
    "preview": false
  }
]

export const branchConfigAbridged = "name = \"ms/theme-conduit\"\n\npost_deploy_runbooks = [\"pipeline-health-sweep\"]\n\n[public_repo]\nrepo      = \"nuonco/kitchen-sink\"\ndirectory = \".\"\nbranch    = \"ms/theme-conduit\"\n\n[[install_groups]]\nname  = \"staging\"\norder = 1\nuse_for_previews = true\n\n[install_groups.label_selector]\nenv = \"staging\"\n\n[[install_groups]]\nname  = \"customers\"\norder = 2\n\n[install_groups.label_selector]\nenv  = \"production\"\ntier = \"customer\"\n\n[[install_groups]]\nname  = \"enterprise\"\norder = 3\n\n[install_groups.label_selector]\nenv  = \"production\"\ntier = \"enterprise\""

export const runbooks: Runbook[] = [
  {
    "name": "pipeline-health-sweep",
    "description": "Check an install end to end: nodes, the Conduit workloads, the ALB ingress, the public HTTPS endpoint, and whether syncs are actually landing.",
    "kind": "health-check",
    "mutates": false,
    "steps": [
      {
        "name": "node-health",
        "type": "action",
        "detail": "Nodes, Node capacity · 2m"
      },
      {
        "name": "workload-health",
        "type": "action",
        "detail": "runs the sync_heartbeat action"
      },
      {
        "name": "rollout-convergence",
        "type": "action",
        "detail": "rollout status, Horizontal pod autoscalers · 6m"
      },
      {
        "name": "ingress-health",
        "type": "action",
        "detail": "Helm releases in conduit, ALB ingress · 3m"
      },
      {
        "name": "endpoint-health",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 5m"
      },
      {
        "name": "sync-freshness",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 2m"
      }
    ]
  },
  {
    "name": "debug-bundle",
    "description": "Something's gone wrong — collect a read-only diagnostic bundle: pod state, events, logs, restart reasons, and a verbose endpoint probe.",
    "kind": "debug",
    "mutates": false,
    "steps": [
      {
        "name": "collect-diagnostics",
        "type": "action",
        "detail": "runs the debug action"
      },
      {
        "name": "workload-detail",
        "type": "action",
        "detail": "Deployments, Pods, Pod detail, Worker logs, Postgres logs · 4m"
      },
      {
        "name": "ingress-and-secrets",
        "type": "action",
        "detail": "Services and ingresses, ALB ingress detail, Synced secrets present, Config map · 3m"
      },
      {
        "name": "endpoint-probe",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 2m"
      }
    ]
  },
  {
    "name": "reconcile-drift",
    "description": "Re-apply desired state after out-of-band changes: plan the chart, reprovision the sandbox, then roll the infrastructure and app components forward.",
    "kind": "drift",
    "mutates": true,
    "steps": [
      {
        "name": "drift-plan",
        "type": "component_deploy",
        "detail": "conduit, plan only"
      },
      {
        "name": "reconcile-sandbox",
        "type": "sandbox_reprovision",
        "detail": "sandbox infrastructure, component deploys skipped"
      },
      {
        "name": "reconcile-destination-bucket",
        "type": "component_deploy",
        "detail": "destination_bucket"
      },
      {
        "name": "reconcile-certificate",
        "type": "component_deploy",
        "detail": "certificate"
      },
      {
        "name": "reconcile-app",
        "type": "component_deploy",
        "detail": "conduit, dependents follow"
      },
      {
        "name": "verify",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 8m"
      }
    ]
  },
  {
    "name": "pause-pipelines",
    "description": "Emergency pause of every sync pipeline, run as a recorded, elevated procedure instead of ad-hoc console access — then verified and resumed.",
    "kind": "break-glass",
    "mutates": true,
    "steps": [
      {
        "name": "capture-state",
        "type": "action",
        "detail": "Pods before the pause, Recent events · 3m"
      },
      {
        "name": "pause-and-verify",
        "type": "action",
        "detail": "runs the pause_pipelines action"
      },
      {
        "name": "verify",
        "type": "action",
        "detail": "probe the public HTTPS endpoint · 8m"
      }
    ]
  }
]

export const adhocActions: AdhocAction[] = [
  {
    "name": "sync_heartbeat",
    "timeout": "2m",
    "triggers": [
      "cron 0 * * * *",
      "manual"
    ],
    "labels": "is_health_check = \"true\"",
    "breakGlass": false
  },
  {
    "name": "debug",
    "timeout": "2m",
    "triggers": [
      "manual"
    ],
    "labels": null,
    "breakGlass": false
  },
  {
    "name": "lifecycle_hooks",
    "timeout": "1m",
    "triggers": [
      "manual",
      "post-provision",
      "post-deploy-component conduit",
      "pre-deploy-component conduit"
    ],
    "labels": null,
    "breakGlass": false
  },
  {
    "name": "pause_pipelines",
    "timeout": "10m",
    "triggers": [
      "manual"
    ],
    "labels": "is_break_glass = \"true\"",
    "breakGlass": true
  }
]

export const lifecycleHooksToml = "name         = \"lifecycle_hooks\"\ntimeout      = \"1m\"\ndependencies = [\"conduit\"]\n\n[[triggers]]\ntype = \"manual\"\n\n[[triggers]]\ntype = \"post-provision\"\n\n[[triggers]]\ntype           = \"post-deploy-component\"\ncomponent_name = \"conduit\"\n\n[[triggers]]\ntype           = \"pre-deploy-component\"\ncomponent_name = \"conduit\"\n\n[[steps]]\nname            = \"log-lifecycle-hook\"\ninline_contents = \"./lifecycle_hooks/script.sh\"\n\n[steps.env_vars]\nHOOK_VERSION = \"v1\""

export const roles: Role[] = [
  {
    "name": "provision",
    "type": "provision",
    "boundary": "provision_boundary.json",
    "desc": "Provision the sandbox and components; trigger actions."
  },
  {
    "name": "setup",
    "type": "custom",
    "boundary": "provision_boundary.json",
    "desc": "Initial component deployment and configuration."
  },
  {
    "name": "maintenance",
    "type": "maintenance",
    "boundary": "maintenance_boundary.json",
    "desc": "Operate and remediate components."
  },
  {
    "name": "sandbox-updates",
    "type": "custom",
    "boundary": "provision_boundary.json",
    "desc": "Update and maintain sandbox infrastructure."
  },
  {
    "name": "actions",
    "type": "custom",
    "boundary": "inline policy",
    "desc": "Execute actions (healthchecks, debug, cron jobs)."
  },
  {
    "name": "deprovision",
    "type": "deprovision",
    "boundary": "deprovision_boundary.json",
    "desc": "Deprovision the sandbox and components."
  },
  {
    "name": "app-break-glass",
    "type": "break-glass",
    "boundary": "explicit Deny",
    "desc": "Admin access for emergencies, minus Secrets Manager; every use is recorded."
  }
]

export const breakGlassToml = "[[role]]\nname         = \"{{.nuon.install.id}}-app-break-glass\"\ndisplay_name = \"Break Glass Admin\"\ndescription  = \"admin access for emergencies, minus Secrets Manager; every use is recorded\"\n\n[[role.policies]]\nmanaged_policy_name = \"AdministratorAccess\"\n\n[[role.policies]]\nname     = \"remove-secrets-manager\"\ncontents = \"\"\"\n{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Deny\",\n            \"Action\": \"secretsmanager:*\",\n            \"Resource\": \"*\"\n        }\n    ]\n}\n\"\"\""

export const guardrails: Guardrail[] = [
  {
    "name": "cluster-requirements",
    "type": "sandbox",
    "target": "the sandbox plan"
  },
  {
    "name": "deny-public-api-ingress",
    "type": "helm_chart",
    "target": "conduit"
  },
  {
    "name": "deny-public-s3-bucket",
    "type": "terraform_module",
    "target": "all components"
  },
  {
    "name": "sandbox-limits",
    "type": "sandbox",
    "target": "the sandbox plan"
  }
]

export const toggleableComponents: ToggleableComponent[] = [
  {
    "name": "compliance_export",
    "type": "kubernetes_manifest",
    "defaultEnabled": false,
    "toml": "name = \"compliance_export\"\ntype = \"kubernetes_manifest\"\n\nnamespace    = \"conduit\"\ndependencies = [\"conduit\"]\n\ntoggleable      = true\ndefault_enabled = false\n\n[public_repo]\ndirectory = \".\"\nrepo      = \"nuonco/kitchen-sink\"\nbranch = \"ms/theme-conduit\"\n\n[kustomize]\npath        = \"./src/components/compliance-export\"\npatches     = []\nenable_helm = false\n\n[labels]\ntoggleable = \"true\""
  },
  {
    "name": "tictactoe",
    "type": "kubernetes_manifest",
    "defaultEnabled": false,
    "toml": "name = \"tictactoe\"\ntype = \"kubernetes_manifest\"\n\nnamespace    = \"conduit\"\ndependencies = [\"conduit\"]\n\ntoggleable      = true\ndefault_enabled = false\n\n[public_repo]\ndirectory = \".\"\nrepo      = \"nuonco/kitchen-sink\"\nbranch = \"ms/theme-conduit\"\n\n[kustomize]\npath        = \"./src/components/tictactoe\"\npatches     = []\nenable_helm = false\n\n[labels]\ntoggleable = \"true\""
  }
]
