name               = "db_metrics"
image              = "postgres:17-alpine"
timeout            = "5m"
enable_kube_config = false

[[triggers]]
type = "manual"

[[steps]]
name            = "query-metrics"
inline_contents = "./db_metrics/metrics.sh"

[steps.env_vars]
PGHOST            = "{{.nuon.install_stack.outputs.custom_nested_stacks.cloudsql_instance.outputs.DBEndpoint}}"
PGPORT            = "{{.nuon.install_stack.outputs.custom_nested_stacks.cloudsql_instance.outputs.DBPort}}"
PGUSER            = "kitchensink"
PGDATABASE        = "postgres"
GCP_DB_SECRET     = "{{.nuon.install_stack.outputs.db_password_secret_name}}"
PGCONNECT_TIMEOUT = "10"

[labels]
runtime = "container"
sample  = "db-metrics"
