name         = "api_token"
display_name = "API Token abc"
description  = "Token for external API integration"
group        = "compute"
type         = "string"
required     = false
sensitive    = true
