name              = "instance_type"
display_name      = "Node Instance Size"
description       = "EC2 instance type for EKS worker nodes"
group             = "compute"
default           = "t3a.medium"
type              = "string"
required          = false
user_configurable = true
