# action
name    = "uptime_heartbeat"
timeout = "1m"

[[triggers]]
type          = "cron"
cron_schedule = "0 * * * *"

[[triggers]]
type = "manual"

[[steps]]
name            = "collect-status"
inline_contents = "./uptime_heartbeat/script.sh"

[labels]
is_health_check = "true"
