name            = "jm-test-001"
approval_option = "approve-all"

[labels]
env    = "staging"
region = "us-west-2"

[aws_account]
region = "us-west-2"

# input.group: compute
[[inputs]]
instance_type = "t3a.small"
debug_mode    = "false"

# input.group: dns
[[inputs]]
domain = "jm-test-001.nuon.run"
