# action
name         = "db_indexes"
image        = "{{.nuon.components.action_db_tools.outputs.image.ref}}"
timeout      = "5m"
dependencies = ["action_db_tools"]

[[triggers]]
type = "manual"

[[steps]]
name            = "inspect indexes"
inline_contents = "./db_indexes/indexes.sh"

[steps.env_vars]
PGHOST            = "{{.nuon.install_stack.outputs.custom_nested_stacks.rds_instance.outputs.DBEndpoint}}"
PGPORT            = "{{.nuon.install_stack.outputs.custom_nested_stacks.rds_instance.outputs.DBPort}}"
PGUSER            = "kitchensink"
PGDATABASE        = "postgres"
PGPASSWORD        = "temp-password-123"
PGCONNECT_TIMEOUT = "10"
