# helm

name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["certificate", "kitchen_sink"]
max_auto_retries = 5

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "src/components/alb"
branch    = "cb/reconfigure-ui"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "app.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
https_port         = "443"
service_name       = "kitchen-sink-ui"
service_port       = "3000"
install_name       = "{{.nuon.install.id}}"
namespace          = "kitchen-sink"
healthcheck_path   = "/livez"
