name = "kitchen_sink_docker_build"
type = "docker_build"

dockerfile = "Dockerfile"

dependencies = ["kitchen_sink_ecr_image"]

[connected_repo]
directory = ""
repo      = "nuonco/kitchen-sink"
branch    = "main"
