name = "kitchen_sink_ecr_image"
type = "container_image"

dependencies = ["kitchen_sink_external_image"]

[aws_ecr]
image_url    = "ecr-image-repository"
tag          = "latest"
region       = "us-east-1"
iam_role_arn = "ecr-access-iam-role-arn"
