name       = "kitchen_sink_helm"
type       = "helm_chart"
chart_name = "kitchen-sink"

namespace      = "{{.nuon.install.id}}"
storage_driver = "configmap"
drift_schedule = "0 * * * *"

dependencies = ["kitchen_sink_image"]

[connected_repo]
directory = "chart"
repo      = "nuonco/kitchen-sink"
branch    = "main"

[values]
"api.ingresses.public_domain"   = "api.{{.nuon.install.public_domain}}"
"api.ingresses.internal_domain" = "api.{{.nuon.install.internal_domain}}"
"ui.ingresses.public_domain"    = "dashboard.{{.nuon.install.public_domain}}"
"ui.ingresses.internal_domain"  = "dashboard.{{.nuon.install.internal_domain}}"
"env.DEFAULT_VALUE"             = "set-by-terraform-provider-as-default"
"env.NUON_APP_ID"               = "{{.nuon.app.id}}"
"env.NUON_ORG_ID"               = "{{.nuon.org.id}}"
"env.NUON_INSTALL_ID"           = "{{.nuon.install.id}}"

# Container image outputs
"env.IMAGE_URL" = "{{.nuon.components.kitchen_sink_image.image.url}}"
"env.IMAGE_TAG" = "{{.nuon.components.kitchen_sink_image.image.tag}}"

# Sandbox outputs
"env.SANDBOX_TYPE"            = "{{.nuon.install.sandbox.type}}"
"env.SANDBOX_PUBLIC_DOMAIN"   = "{{.nuon.install.public_domain}}"
"env.SANDBOX_INTERNAL_DOMAIN" = "{{.nuon.install.internal_domain}}"
