# Runs when a release/v* tag points at a commit reachable from main.
name = "tagged-release"
post_deploy_runbooks = ["full-health-check"]

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "."
branch    = "main"

[run]
mode       = "on_tag_prefix"
tag_prefix = "release/"

[[install_groups]]
name  = "staging"
order = 1

[install_groups.label_selector]
env = "staging"

[[install_groups]]
name  = "customers"
order = 2

[install_groups.label_selector]
env  = "production"
tier = "customer"

[[install_groups]]
name  = "enterprise"
order = 3

[install_groups.label_selector]
env  = "production"
tier = "enterprise"
