# branch
# this branch is updated when a git tag is pushed with the provided prefix
name = "tag-release"

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "."
branch    = "main"

[run]
mode = "on_tag"
tag_prefix = "app-branch-release/"

[[install_groups]]
name  = "tag"
order = 1

[install_groups.label_selector]
mode = "on_tag_prefix"
