name         = "rollout_status"
image        = "alpine/k8s:1.34.1"
timeout      = "10m"
dependencies = ["kitchen_sink"]

[[triggers]]
type = "manual"

[[steps]]
name            = "rollout-status"
inline_contents = "./rollout_status/rollout.sh"

[labels]
runtime = "container"
sample  = "kubectl"
