name              = "db_tier"
display_name      = "Cloud SQL Tier"
description       = "Cloud SQL machine tier"
group             = "compute"
default           = "db-f1-micro"
type              = "string"
required          = false
user_configurable = true
