name                  = "Kitchen Sink Installer"
description           = "Install the Kitchen Sink App into your cloud account"
documentation_url     = "https://docs.nuon.co"
community_url         = "https://community.nuon.co"
homepage_url          = "https://nuon.co"
github_url            = "https://github.com/nuonco/kitchen-sink-app"
logo_url              = "https://nuon.co/logo.png"
demo_url              = "https://demo.nuon.co"
favicon_url           = "https://nuon.co/favicon.ico"
og_image_url          = "https://nuon.co/og-image.png"
post_install_markdown = "Your Kitchen Sink App is now installed! Visit the UI at the public domain shown above."
footer_markdown       = "Powered by [Nuon](https://nuon.co)"
copyright_markdown    = "© 2024 Nuon, Inc."
