# runner
runner_type     = "aws"
helm_driver     = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/a7120dba1d64b3ab4fb68568b87e0305ee8d620a/scripts/aws/init-mng.sh"

[env_vars]
HELM_MAX_HISTORY = "10"
