name            = "nuon-test-002"
approval_option = "approve-all"

[labels]
env    = "production"
region = "us-east-1"
tier   = "customer"

[aws_account]
region = "us-east-1"

[[inputs]]
instance_type = "t3a.medium"
debug_mode    = "false"
