# install
name = "Customer E"
app_branch = "tag-release"
approval_option = "approve-all"

[labels]
mode = "on_tag_prefix"

[gcp_account]
project_id = "acme-kitchen-sink-stage"
region     = "us-west1"

[[inputs]]
debug_mode = "false"

[[inputs]]
db_tier = "db-f1-micro"

[[inputs]]
domain = "stage.nuon.run"

[component_toggles]
audit_log_exporter = false
tictactoe          = false
