# pulumi
name    = "pulumi_infra"
type    = "pulumi"
runtime = "go"

[public_repo]
repo      = "nuonco/kitchen-sink"
directory = "components/pulumi"
branch    = "main"

[config]
"aws:region"                 = "{{.nuon.install_stack.outputs.region}}"
"kitchen-sink:install_id"    = "{{.nuon.install.id}}"

[env_vars]
PULUMI_SKIP_UPDATE_CHECK = "true"

[labels]
custom_component_type = "pulumi"
