type           = "deprovision"
name           = "{{.nuon.install.id}}-deprovision"
description    = "deprovision the sandbox and components."
display_name   = "deprovision role"
cloud_platform = "gcp"

[[policies]]
name                = "owner"
gcp_predefined_role = "roles/owner"
