name         = "describe_cert"
image        = "{{.nuon.components.action_gcloud.outputs.image.ref}}"
timeout      = "5m"
dependencies = ["action_gcloud", "certificate"]

[[triggers]]
type = "manual"

[[steps]]
name            = "describe certificate"
inline_contents = "./describe_cert/describe_cert.sh"

[steps.env_vars]
CERTIFICATE_NAME = "{{.nuon.components.certificate.outputs.certificate_name}}"
CERT_MAP_NAME     = "{{.nuon.components.certificate.outputs.cert_map_name}}"
PROJECT_ID        = "{{.nuon.install_stack.outputs.project_id}}"
