# permission
type                 = "maintenance"
name                 = "{{.nuon.install.id}}-maintenance"
description          = "operate and remediate components"
display_name         = "maintenance role"
permissions_boundary = "./maintenance_boundary.json"

[[named_policies]]
name = "{{.nuon.install.id}}-alb-maintenance"

[[policies]]
managed_policy_name = "AdministratorAccess"
