# sandbox
terraform_version = "1.11.3"

[public_repo]
directory = "."
repo      = "nuonco/aws-eks-auto-sandbox"
branch    = "main"

[vars]
cluster_name    = "n-{{.nuon.install.id}}"
cluster_version = "1.34"

region = "{{.nuon.install_stack.outputs.region}}"
vpc_id = "{{.nuon.install_stack.outputs.vpc_id}}"

enable_nuon_dns      = "true"
public_root_domain   = "{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"
internal_root_domain = "internal.{{ .nuon.install.id }}.{{.nuon.inputs.inputs.domain}}"

public_subnet_ids    = "{{.nuon.install_stack.outputs.public_subnets}}"
private_subnet_ids   = "{{.nuon.install_stack.outputs.private_subnets}}"
runner_subnet_id     = "{{.nuon.install_stack.outputs.runner_subnet}}"

[[var_file]]
contents = "./sandbox.tfvars"
